apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/image-one
  - ../../bases/common/ingress.yaml

images:
  - name: veerapaku/argocd-app
    newTag: "3.0"

namespace: myapp-imageone

namePrefix: dev-