apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/image-one

images:
  - name: veerapaku/argocd-app
    newTag: "4.0"

namespace: myapp-imageone

namePrefix: dev-