apiVersion: v1
kind: Service
metadata:
  name: pokemonreviewapp-service
spec:
  selector:
    app: dotnet
  type: NodePort
  ports:
    - name: pokemonreviewapp
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
