kubernetes apiVersion: v1
kind: Service
metadata:
  name: pokemonreviewapp-service
spec:
  type: NodePort
  selector:
    app: dotnet
  ports: 
  - name: pokemonreviewapp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080