apiVersion: v1
kind: Service
metadata:
  name: pokemonreviewapp-service
  namespace: dotnet  # ✅ Add this
spec:
  selector:
    app: dotnet
  type: LoadBalancer
  ports:
    - name: pokemonreviewapp
      port: 8080
      targetPort: 8080
      # nodePort: 30080
      protocol: TCP
