apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
images:
- name: veerapaku/argocd-app
  newTag: "1.0"

resources:
- ../../bases/image-three
- ../../bases/common/ingress.yaml

namespace: myapp-imagethree
namePrefix: dev-