apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: recursing_golick
        image: veerapaku/argocd:imagetwo-2.0
        ports:
        - containerPort: 5003
        resources:
          requests:
            memory: "256Mi"  # Minimum memory requested by the container
            cpu: "500m"      # Minimum CPU requested by the container
          limits:
            memory: "512Mi"  # Maximum memory the container can use
            cpu: "1"         # Maximum CPU the container can use
