apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      containers:
      - name: distracted-maxwell
        image: veerapaku/argocd:imagethree-3.0
        ports:
        - containerPort: 5004
        resources:
          requests:
            memory: "256Mi"  # Minimum memory requested by the container
            cpu: "500m"      # Minimum CPU requested by the container
          limits:
            memory: "512Mi"  # Maximum memory the container can use
            cpu: "1"         # Maximum CPU the container can use
