apiVersion: v1
kind: Service
metadata:
  name: myapp-service2
spec:
  selector:
    app: myapp-deployment
  ports:
  - port: 8080           # Port exposed by the service
    protocol: TCP
    targetPort: 5003      # Port on which the container is listening
