apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080           # Port exposed by the service
    protocol: TCP
    targetPort: 5002      # Port on which the container is listening
