apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/dotnet-webapi

images:
  - name: veerapaku/pokemonreviewapp
    newTag: "latest"

namespace: dotnet

namePrefix: dev-