apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-imagetwo
spec:
  selector:
    matchLabels:
      app: myapp-imagetwo
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-imagetwo
    spec:
      containers:
      - name: imagetwocontainer
        image: veerapaku/argocd-app:2.0
        ports:
        - containerPort: 5005
        env:
          - name: GREETING_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                namespace: myapp-imagtwo
                key: GREETING_MESSAGE
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        livenessProbe:       # Checks if the app is still alive — if it fails repeatedly, the container will be restarted.
          httpGet:
            path: /
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:     # Checks if the app is ready to receive traffic — if it fails, the pod is removed from the Service endpoints.
          httpGet:
            path: /
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3