apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-imagetwo
spec:
  selector:
    matchLabels:
      app: myapp-imagetwo
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-imagetwo
    spec:
      containers:
      # - name: recursing-golick
      #   image: veerapaku/argocd:imageone-1.0
      #   ports:
      #   - containerPort: 5002
      #   resources:
      #     requests:
      #       memory: "256Mi"
      #       cpu: "500m"
      #     limits:
      #       memory: "512Mi"
      #       cpu: "1"
      - name: imagetwocontainer
        image: veerapaku/argocd-app:2.0
        ports:
        - containerPort: 5005
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      # - name: distracted-maxwell
      #   image: veerapaku/argocd:imagethree-3.0
      #   ports:
      #   - containerPort: 5004
      #   resources:
      #     requests:
      #       memory: "256Mi"  # Minimum memory requested by the container
      #       cpu: "500m"      # Minimum CPU requested by the container
      #     limits:
      #       memory: "512Mi"  # Maximum memory the container can use
      #       cpu: "1"         # Maximum CPU the container can use
