apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
images:
- name: veerapaku/argocd-app
  newTag: "2.0"

resources:
- ../../bases/image-two
- ../../bases/common/ingress.yaml

namespace: myapp-imagetwo
namePrefix: dev-