apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-imagethree
spec:
  selector:
    matchLabels:
      app: myapp-imagethree
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-imagethree
    spec:
      containers:
      # - name: recursing-golick
      #   image: veerapaku/argocd:imageone-1.0
      #   ports:
      #   - containerPort: 5002
      #   resources:
      #     requests:
      #       memory: "256Mi"
      #       cpu: "500m"
      #     limits:
      #       memory: "512Mi"
      #       cpu: "1"
      # - name: festive-khayyam
      #   image: veerapaku/argocd:imagetwo-2.0
      #   ports:
      #   - containerPort: 5003
      #   resources:
      #     requests:
      #       memory: "256Mi"
      #       cpu: "500m"
      #     limits:
      #       memory: "512Mi"
      #       cpu: "1"
      - name: imageonecontainer
        image: veerapaku/argocd-app:1.0
        ports:
        - containerPort: 5004
        resources:
          requests:
            memory: "256Mi"  # Minimum memory requested by the container
            cpu: "500m"      # Minimum CPU requested by the container
          limits:
            memory: "512Mi"  # Maximum memory the container can use
            cpu: "1"         # Maximum CPU the container can use
