# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: myapp-config
#   namespace: myapp-imagethree
# data:
#   GREETING_MESSAGE: "Hello from ConfigMap!"
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp-imagetwo
data:
  GREETING_MESSAGE: "Hello from ConfigMap!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp-imageone
data:
  GREETING_MESSAGE: "Hello from ConfigMap!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-kubelet-check
  namespace: datadog
  labels:
    ad.datadoghq.com/checks: "true"
data:
  kubelet.d_conf.yaml: |
    init_config:
    instances:
      - kubelet_tls_verify: false