apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgByJ9Tm...<encrypted blob>
  template:
    metadata:
      name: datadog-secret
      namespace: datadog
    type: Opaque
