apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    site: datadoghq.eu
    clusterName: minikube     
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  overrides:
    agent:
      config:
        configMapName: datadog-kubelet-check
        configMapItems:
          - key: kubelet.d_conf.yaml
            path: kubelet.d/conf.yaml
