apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    site: datadoghq.eu
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  override:
    agent:
      config:
        configMapName: kubelet-check
        configMapItems:
          - key: conf.yaml
            path: kubelet.d/conf.yaml