apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp-imagethree
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: image-three.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-imagethree-service
            port:
              number: 5004

  - host: image-two.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-imagetwo-service
            port:
              number: 5005

  - host: image-one.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-imageone-service
            port:
              number: 5006
