apiVersion: v1
kind: Service
metadata:
  name: myapp-imageone-service
spec:
  selector:
    app: myapp-imageone  # Matches the label in your Deployment
  ports:
    - name: imagethreecontainer    # Unique name for the first port
      protocol: TCP
      port: 5006                     # Port exposed by the Service for recursing-golick
      targetPort: 5006               # Target port on the recursing-golick container
  type: ClusterIP      # Exposes the service within the Kubernetes cluster
